spring:
  profiles: local
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.3.158:3306/pureshare_higou?useSSL=false&characterEncoding=utf8
    username: root
    password: 123456
  jpa:
    database: mysql
logging:
  level:
    com.zhksufsc: DEBUG